version: "3.9"
services:
  golang:
    build:
      context: .
      dockerfile: dockerfiles/go.util.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend/go-api:/go:rw

  api:
    build:
      context: .
      dockerfile: dockerfiles/go.api.dockerfile